/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BingoCards": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BingoProgress": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CallBingoFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CompletedBingo": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Events": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "GameStateFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GameWebSocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "Games": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "JoinFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MarkWordFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "NewGameFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Players": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ResetGameFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TestUsernameFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdateProfileFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "UserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "WSAuthorizerFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WSConnectHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WSDisconnectHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WSMessageHandler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Words": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}